%%Script to test Wcu outputs against David A. Winter Butterworth filer correction outputs.
close all
clear

filter_order = 2;
filter_passes = 2; 	                    % filtfilt function uses 2 passes
sampling_frequency = 2000;
cutoff_frequency = 20;
C = (((2^(1/filter_passes))-1)^(1/4));  % Winter correction factor
Wc = 2*pi*cutoff_frequency; 		    % angular cutoff frequency
Uc = tan(Wc/(2*sampling_frequency)); 	% adjusted angular cutoff frequency
Un = Uc / C; 							% Winter correction
f_corrected = atan(Un)*sampling_frequency/pi;  % corrected cutoff frequency
[b, a] = butter(filter_order, f_corrected/(sampling_frequency/2), 'low');
%signal_filtered = filtfilt(b, a, data);

%Function code:
[cu_corrected, order_corrected]=Wcu(filter_order*2, cutoff_frequency, 'low', sampling_frequency);
[B,A] = butter(order_corrected, cu_corrected/(sampling_frequency/2), 'low');

if sum(A-a) == 0 && sum(B-b) == 0
    if filter_order == 2
        disp(['Wcu outputs are the same as those generated by the Winter correction factor for a ',num2str(filter_order),'nd-order filter.'])
    else
        disp(['Wcu outputs are the same as those generated by the Winter correction factor for a ',num2str(filter_order),'th-order filter.'])
    end
else
    disp(['Wcu outputs and those generated by the Winter correction factor are not the same for a ',num2str(filter_order),'th-order filter.'])
end